version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: MYSQLPHP
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mainDB
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpSQL
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - db
    networks:
      - dbnetwork

  web:
    build:
      context: .
    container_name: django-app
    command: >
      sh -c "./wait-for.sh db python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dbnetwork

networks:
  dbnetwork:

volumes:
  db_data:
